### ISSUE TITLE
Build on Mac

### ISSUE THREAD

**Issue by mshkrebtan** [quiris11/ExtractCoverThumbs#2]
Could you please tell me how to build the app with pyinstaller?

First, I got a warning:

```
You appear to be using an ActiveTcl build of Tcl/Tk, which PyInstaller has
difficulty freezing. To fix this, comment out all references to "teapot" in:

     /Library/Frameworks/Tcl.framework/Versions/8.5/Resources/Scripts/init.tcl

See https://github.com/pyinstaller/pyinstaller/issues/621 for more information.
```

Then I commented the teapot references, and pyinstaller could build an executable. But when I launch it I get:

```
tcl/auto.tcl could not be extracted!
```

What do I do with that? I can’t even google any working solution. Maybe you know?

**Comment by quiris11** [comment]
On Windows? 
1) I have installed official Python 2.7.11 (32-bit)
2) python -m pip install pillow
3) python -m pip install pyinstaller

If you have ExtractCoverThumbs extracted do C:\
4) C:\Python27\Scripts\pyinstaller.exe -Fn ExtractCoverThumbs_win --windowed C:\ExtractCoverThumbs\gui.py

**Comment by quiris11** [comment]
On Mac OS X:

1) First I installed Python 2.7.11 via Homebrew: http://brew.sh
2) python -m pip install pillow
3) python -m pip install pyinstaller
4) pyinstaller -Fn ExtractCoverThumbs_app  --windowed ~/github/ExtractCoverThumbs/gui.py

**Comment by quiris11** [comment]
Python 2.7.11 (default, Dec 26 2015, 17:47:15) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

**Comment by mshkrebtan** [comment]
Thank you! I’ve switched to Homebrew’s Python and it worked easily.
