### ISSUE TITLE
Cover overwrite overwrites all PDOC covers, not just AZW3?

### ISSUE THREAD

**Issue by HamsterExAstris** [quiris11/ExtractCoverThumbs#3]
When trying to use v0.8.1's new feature to overwrite existing Personal Document covers, it overwrote both AZW and AZW3 covers. I would expect it to _only_ overwrite AZW3 covers when the "Extract covers from AZW files" box isn't checked.

Log snippet, from a run with only the "Overwrite existing personal document (PDOC) covers?" box checked, no others:
- Balance Point.azw3_RYMJFYQRBE3ZXGWES3BSOBWFJ4JMA6UQ.azw3: EXTRACTING COVER: DONE!
- Baneblade.azw3_JKP4MAYU7YCWOBUIXQ7SHMOVW5WPXTRG.azw3: EXTRACTING COVER: DONE!
- Battle Of The Fang.azw_TUNXCC2QF5AC2NA3QUJOJV52XYSFJ7I2.azw: EXTRACTING COVER: DONE!

I would not have expected that third book to be processed.

Based on the current code online it seems like this _should_ work as expected; I don't see any obvious bug in the AZW vs AZW3 handling...

This wasn't the only affected book in the run. I can provide the full log if needed.

**Comment by quiris11** [comment]
Thank you for the bug report. It's fixed in source now. You can download the latest tree and use it or wait for next release.
